### PR TITLE
Add last update to readme

### PR DESCRIPTION
**Pull request by chmac**
This is a pretty useless PR. I mostly wanted to reach out and see if you have any plans to continue this project or might be open to collaboration. I'm really interested in working on apps which store user data in git repositories in standard, simple, plain text formats like markdown, yaml, etc. One of my big targets is a bookmarking tool, so looking at what already exists that might fit this remit...

### CODE REVIEW

**Comment by barfuin** [comment]
Well, thank you for reaching out! Frankly, I didn't expect anyone to be interested in this project yet. 😄 But, that's great!

The project is currently dormant, as I spend my time on other projects at the moment, but it's not abandoned. If you'd be willing to contribute new features and some much-needed updates, I'd greatly appreciate it. Some initial functionality is already there, such as adding a new bookmark, and creating the Jekyll input for rendering a complete initial site. That's a starting point at least.  
And I have the pagemarks.io domain. 😄

What are your plans / ideas?

**Comment by barfuin** [comment]
Given the possibility of someone else working on this, I scanned my local drive and found some changes, which I just pushed. They seem to include some changes to existing commits, so you may have to force pull it once.

**Comment by chmac** [comment]
@barfuin Are you open to enabling issues on this repo? Then we’d have somewhere to discuss which might be easier than a nonsense PR! :-)

I’m interested in storing all kinds of data in git. I’m especially interested in cross compatibility between different software that could share the same git repo. I’m personally more experienced with Gatsby than with Jekyll, but I’d definitely be happy to look at your code and see if I could use it for my bookmarks as a starting point.

Right now my personal issue is I can’t easily save bookmarks, and I have a lot already. So I’m looking to get something running soon which stores the actual data in plain text in git. If the front end is Jekyll, that would work.

**Comment by barfuin** [comment]
Sure, just enabled issues for this repo.

Looking forward to hearing about your concrete suggestions and plans.

**Comment by barfuin** [comment]
I hope it's ok for you when I close this PR, as we have issues available now. 😊

**Pull request closed without merging**
